#ifndef __ROBOPET_CONSTANTS_H__
#define __ROBOPET_CONSTANTS_H__

//---- MEASURES ----
#define ARENA_WIDTH_MM 7400
#define ARENA_HEIGHT_MM 5400

#define FIELD_WIDTH 6050f
#define FIELD_HEIGHT 4050f

#define FIELD_CENTER_X FIELD_WIDTH/2 + BORDER
#define FIELD_CENTER_Y FIELD_HEIGHT/2 + BORDER

#define ROBOT_RADIUS_MM 90
#define BALL_RADIUS_MM 43

#endif
