/*
	Lua bindings for class Point
	This file was automatically generated by cpptolua

*/

#include "point.h"

extern "C" {
	#include "lua.h"
	#include "lauxlib.h"
	#include "lualib.h"

}

int Point_getDistanceY(lua_State* L);
int Point_getDistanceX(lua_State* L);
int Point_getDistance(lua_State* L);
int Point_setXY(lua_State* L);
int Point_setXY(lua_State* L);
int Point_setY(lua_State* L);
int Point_setX(lua_State* L);
int Point_getY(lua_State* L);
int Point_getX(lua_State* L);
int Point_new(lua_State* L);
int Point_gc(lua_State* L);
Point* toPoint(lua_State *L, int index);
Point* checkPoint(lua_State *L, int index);
int copyPoint(lua_State *L, Point *p);
int luaopen_Point(lua_State *L);
