/*
	Lua bindings for class PhysicsRobot
	This file was automatically generated by cpptolua

*/

#include "physicsRobot.h"

extern "C" {
	#include "lua.h"
	#include "lauxlib.h"
	#include "lualib.h"

}

int PhysicsRobot_getAngle(lua_State* L);
int PhysicsRobot_update(lua_State* L);
int PhysicsRobot_stop(lua_State* L);
int PhysicsRobot_move(lua_State* L);
int PhysicsRobot_rotate(lua_State* L);
int PhysicsRobot_go(lua_State* L);
int PhysicsRobot_fakeMove(lua_State* L);
PhysicsRobot* toPhysicsRobot(lua_State *L, int index);
PhysicsRobot* checkPhysicsRobot(lua_State *L, int index);
int copyPhysicsRobot(lua_State *L, PhysicsRobot *p);
int luaopen_PhysicsRobot(lua_State *L);
